### ISSUE TITLE
Documentation needs updating with exact steps to get something working

### ISSUE THREAD

**Issue by dbellagio** [open-toolchain/toolchain-to-template#12] opened 2020-11-09 08:16 UTC
I've tried multiple times with multiple results.  all not working.
Do I need to generate a token anymore in the file?
I set public cloud to true and it still does not work

**Comment by ejodet** [comment] 2020-11-09 08:36
@dbellagio may you please be more specific and elaborate?
- steps to reproduce
- deviation
Thanks
@maire-kehoe @jauninb ^^

**Comment by jauninb** [comment] 2020-11-09 09:03
@dbellagio assuming that you hit the issue because the url provided is not the URL of a toolchain. The tool needs to be more precise on this error to indicate _for instance_ that the provided url seems not be a URL to a toolchain

**Comment by dbellagio** [comment] 2020-11-09 14:32
@jaunin @ejodet  yeah, my bad, again.  However, last night I had to get something done, so, I jumped back to hand copy them both again.  I went down three paths and did not realize I was in a pipeline and not a toolchain, even though its obvious now 3.5 hours later.......  I spend all my time in this service using pipelines, so, in my mind that it was I want to clone.  Perhaps the tool can get the parent toolchain object if given a pipeline and do what its supposed to do, rather than produce confusing errors messages.  Here is the output now.

Daves-MBP:toolchain dbellagio$ ./toolchain-to-template.sh https://cloud.ibm.com/devops/toolchains/4c0de526-0677-406b-8172-71efeeb0dbdf?env_id=ibm:yp:us-south
Toolchain url is: https://cloud.ibm.com/devops/toolchains/4c0de526-0677-406b-8172-71efeeb0dbdf?env_id=ibm:yp:us-south&isUIRequest=true
Generating toolchain_2020-11-09T08-20-24.yml
Found 0: pipeline
Found 1: hostedgit
Get classic pipeline content: curl -H “Authorization: $BEARER_TOKEN” -H “Accept: application/x-yaml” https://pipeline-service.us-south.devops.cloud.ibm.com/pipeline/pipelines/79077878-4f69-4789-8342-c9482f1815e4
Service hostedgit01 (refers to)-> https://us-south.git.cloud.ibm.com/xcomp-group/ipm-api.git
Classic pipeline content generated: pipeline_pipeline00.yml
The following pipeline secure properties needs to be updated with appropriate values:
DOCKER_PASSWORD
IBMCLOUD_API_KEY
The following stage secure properties needs to be updated with appropriate values:
Cleanup - IBMCLOUD_API_KEY
Output toolchain_2020-11-09T08-20-24.yml file.
Copy pipeline file: pipeline_pipeline00.yml
Template extraction from toolchain ‘ipm-api-bugfix’ done

So, it looks like it worked this time.  However, now I need to figure out how to actually make it active.  I need to create a repo and put this in it.  So, I will see if that works.....

**Comment by ejodet** [comment] 2020-11-09 15:13
right @dbellagio - you may re-work your template based on https://github.com/open-toolchain/sdk/wiki

closing for now

**Closed by ejodet** 2020-11-09 15:13 UTC

**Comment by dbellagio** [comment] 2020-11-09 15:31
@ejodet well, the process is not like any clone process I've used before.  I appear to be stuck trying to see my .bluemix folder through your setup UI.
Is the GIT token a “read-only” token or something more like an “access-token”?   I tried both and I still get the Template Error

**Comment by ejodet** [comment] 2020-11-09 15:35
@dbellagio why don't we discuss this in the [#devops-open-toolchain](https://ibm-cloudplatform.slack.com/archives/C066S82GY) channel for a broader audience?
